### ISSUE TITLE
Can't create Expense invoices  

### ISSUE THREAD

**Issue by nifunifatralara** [quipuapp/quipu-api-php#1]
When trying to crate Expense invoices, there's an issue with the Numeration Series. The API forces us to send a Quipu_Api_Numeration object, but Expenses invoices/tickets have no numeration. 

I've modified class-quipu-api-invoice.php to accept a "kind" item in the attributes array of the invoice, and that seems to have been accepted but I'm stuck with the numeration series

		    "data" => array(
		    	"type" => "invoices",
		    	"attributes" => array(
		    		"kind" => "$order[kind]",
		    		"number" => "$order[number]",
		    		"issue_date" => "$order[issue_date]",
		    		"paid_at" => "$order[paid_at]",
		            "payment_method" => "$order[payment_method]"
				),
				"relationships" => array(
					"contact" => array(
						"data" => array(
							"id" => "$contact_id",
							"type" => "contacts"						
						)
					)
				)

If I send a numeration object (with the invoice number of the expense invoice I have) I get this error:

Message: POST: invoices - Error: not valid for expenses => /data/relationships/book_entry_numeration -

and if I send it empty (null), I get :

Message: POST: numbering_series - Error: Empty Response - Args: Array ( [data] => )

How are we supposed to create expense invoices?

**Comment by nifunifatralara** [comment]
and if I don't send a numeration object at all, the invoice creation just silently fails and does nothing

**Comment by nifunifatralara** [comment]
Just found a solution! in 

replace : 

	public function create_invoice($order) {
		$contact_id = $this->contact->get_id();
		$num_series_id = $this->num_series->get_id();
 

with : 

	public function create_invoice($order) {
		$contact_id = $this->contact->get_id();
		if ($order['kind'] == 'expenses') {
			$num_series_id = '';
		} else {
			$num_series_id = $this->num_series->get_id();
		}	

and then change $postData like this : 

		$postData = array(
		    "data" => array(
		    	"type" => "invoice",
		    	"attributes" => array(
		    		"kind" => "$order[kind]",
		    		"number" => "$order[number]",
		    		"issue_date" => "$order[issue_date]",
		    		"paid_at" => "$order[paid_at]",
		            "payment_method" => "$order[payment_method]"
				),
				"relationships" => array(
					"contact" => array(
						"data" => array(
							"id" => "$contact_id",
							"type" => "contacts"						
						)
					)
				)
		    )
		);

now the $order sent must have a "kind" parameter set ("income" or "expenses")  

and you have to make sure you never call set_numeration() for invoices of type "expenses" when creating the invoice


    	$quipu_invoice->set_contact($contact);

    	if ($order['kind'] == 'income') {
    		$quipu_invoice->set_numeration($numeration);
    	}
 
    	$quipu_invoice->create_invoice($order);

**Comment by nifunifatralara** [comment]
$order must also have a "number" set for expenses invoices to work (that number is the invoice number)

**Comment by albertbellonch** [comment]
Hi @nifunifatralara,

Thanks for contacting us. I'm happy that you found a solution so you can create expenses! 

This first version of the PHP library for Quipu's API was developed with the purpose of allowing ecommerces' (WooCommerce & PrestaShop, for now) order synchronization to work with Quipu. We decided to just implement income invoices for now:

* Only income because it's the synchronizable part of the ecommerce information
* Only invoices in order to keep things as simple as possible for the plugins

Although we will improve the PHP plugin (and finish developing the [Ruby](https://github.com/quipuapp/quipu-api-ruby) one) in the future, we do not have exact plans for that yet. Nevertheless, you can propose changes via pull requests and we will happily accept them.

Regarding this specific issue:

* As you said, no numeration should be set for expenses.
* Number is **not** compulsory for expenses. If it is not set, Quipu will behave as if you used the application directly: it will assign the number after the greatest one set (e.g. if until now the expenses' greatest number is 124, it will assign 125 automatically).

You are more than invited to issue a PR that handles both issues. :)

Best,

PS. You can refer to [the API documentation](http://quipuapp.github.io/api-v1-docs/#attributes) for precise details.

**Comment by albertbellonch** [comment]
HI @nifunifatralara,

Just a clarification on the second part of this issue.

Number is not compulsory but, if it is not set, Quipu will not assign it by default. There are two different numbers for expenses:

- The number appearing in the invoice or ticket you receive: this is NOT compulsory and it's the one available via API.
- The filing number that Quipu will set so our users have a unique number for each one of their expenses. This is the number I was talking about before, NOT to be confused with the one available via API.

I hope everything is clearer now.
